version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./www:/var/www
    depends_on:
      - php
  php:
    build:
      context: ./php-fpm
    container_name: php-fpm
    volumes:
      - ./www:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf.d:/usr/local/etc/php/conf.d
      - ./php-fpm/supervisor:/etc/supervisor
    working_dir: /var/www/html
  mysql:
    image: mysql:5.7.34
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=777
      - MYSQL_USER=777
      - MYSQL_PASSWORD=catch_fuxk
      - MYSQL_ROOT_PASSWORD=catch_fuxk
      - TZ=PRC
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data
  elasticsearch:
    image: elasticsearch:7.12.1
    container_name: elasticsearch
    volumes:
      - ./elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"