version: "3"
services:
  nginx:
    image: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/conf:/etc/nginx/conf.d
      - ./www:/var/www
    depends_on:
      - php
  php:
    build:
      context: ./php-fpm
    volumes:
      - ./www:/var/www
      - ./php-fpm/php.ini:/usr/local/etc/php/php.ini
      - ./php-fpm/conf.d:/usr/local/etc/php/conf.d
  mysql:
    image: mysql:5.7.34
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=777
      - MYSQL_USER=777
      - MYSQL_PASSWORD=catch_fuxk
      - MYSQL_ROOT_PASSWORD=catch_fuxk
      - TZ=PRC
    volumes:
      - ./mysql:/var/lib/mysql
  redis:
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis:/data